### ISSUE TITLE
fix for cpts.php

### ISSUE THREAD

**Issue by DrizzlyOwl** [roikles/Flexbones#39]
Current there are a few errors in cpts.php that need fixing 

1. make use of the variable `$icon` on `line 23`.
2. `$description` variable needs defining at the beginning of the `flexbones_cpts()` function like the others.
3. `line 49` needs the word "Service" removing.
4. `line 54`: the word "Found" needs a space prepending it.

**Comment by roikles** [comment]
Fixed: e682a92db689770481c8a3bb49fa0e26e186c1f1
