### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by roikles** [roikles/Flexbones#45]
We have theme option for an address. I think it would be neat to auto populate some lat/long values for use in Google maps or alternatives. 

I see this working by having 2 additional fields in the theme options `Latitude` and `Longitude`. 

If blank we will auto generate them based on the company postcode upon saving the theme options this way if a user wants to supply values more accurate than the postcode guestimate then they can.

**Comment by roikles** [comment]
@DrizzlyOwl what are your thoughts on this?

**Comment by DrizzlyOwl** [comment]
I think it's definitely going to benefit from use cases where Google Maps api is in use anywhere on the front-end!

Quick thought. If you coupled with `wp_localize_scripts` would it be possible to pass the `lat` and `lng` from php straight into `scripts.js`?

**Comment by roikles** [comment]
wp_localize_scripts does not work well with scalar values: https://core.trac.wordpress.org/ticket/29722?cversion=0&cnum_hist=5

The values for lat/long will be available as php vars. In the prototype I have called them as `data-*` values on the map element like so:

```html
<div id="map" data-latitude="<?php echo flexbones_setting('latitude'); ?>" data-longitude="<?php echo flexbones_setting('longitude'); ?>"></div>
```

**Comment by DrizzlyOwl** [comment]
attribute selectors are nice to use in javascript for fairly competent browsers but has no support for legacy browsers. I can appreciate this is case-specific but something to consider?

**Comment by roikles** [comment]
It shouldn't be an issue in because even IE8 supports `getAttribute`

**Comment by roikles** [comment]
^ Havent tested it yet :smile:

**Comment by DrizzlyOwl** [comment]
I can confirm it works in IE8 using `getAttribute`!

```html
<html id="html" data-lat="1">
[...]
```

```javascript
var lat = document.getElementById('html').getAttribute('data-lat');
console.log(lat) // returns 1
```

**Comment by DrizzlyOwl** [comment]
Confirmed that IE8 supports `getAttribute` e.g.

```html
<div id='foo' data-lat='100'></div>
```
```javascript
console.log( document.getElementById('foo').getAttribute('data-lat') )
```

**Comment by DrizzlyOwl** [comment]
Has this been tackled yet? This ticket got stagnant.

**Comment by roikles** [comment]
I *think* its in there but I will check when I get a moment.

**Comment by roikles** [comment]
this is complete. If you fill in a post code on the theme customizer it should auto generate lat/long values that you can get with `<?php  flexbones_setting('lat')  ?>` or `<?php flexbones_setting('long') ?>`
