### ISSUE TITLE
Load WordPress via Git Submodule

### ISSUE THREAD

**Issue by DrizzlyOwl** [roikles/Flexbones#57]
Has this been considered as an option? specify a stable branch in your git modules and then for those that clone this repo with the `--recursive` option they will get a compatible WordPress build with it.

**Comment by roikles** [comment]
I spoke in our WP group on Slack about this and the general consensus was that git modules is not a great way to go (everyone suggested composer).

I use WP-CLI to install WordPress but If you can justify why this is the best way to go then sell it to me :D

**Comment by DrizzlyOwl** [comment]
1) Using composer means requiring additional pre-requisites.
2) Including a `.gitmodule` is an optional step and can be skipped if the user has a manual zip of WP or uses WP-CLI
3) By adding in a `--recursive` flag when using `git clone <url>` it will bring in a specified version which users will know is compatible with the theme.
