### ISSUE TITLE
browsersync script not using config array

### ISSUE THREAD

**Issue by ollypittaway** [roikles/Flexbones#66]
The browsersync script in package.json doesn't dynamically use the data which is in the Config array,

If the line is replaced with this:

> browser-sync start --files $npm_package_config_theme'*, !'$npm_package_config_theme'**/*.scss, !.git/*, '$npm_package_config_theme'**/*' --no-open --proxy $npm_package_config_watchproxy",

Then it uses the pre defined variables to stop the user having to re-input the information.

**Comment by roikles** [comment]
Can you submit a PR for this and I will merge it now I have tested it.
